Fix non-standard type declaration in convective_diagnostics.F
The convective_diagnostics module defined a couple of double-precision
variables as real*8, which was caught by the GNU compiler with the -std=f2008
flag:

   convective_diagnostics.F:672:11:

     672 |     real*8 :: avgth,avgqv
         |           1
   Error: GNU Extension: Nonstandard type declaration REAL*8 at (1)

Using R8KIND from the mpas_kind_types module, and the declaring these variables
as real(kind=R8KIND) resolves this issue.