Address Fortran 2008 compliance in mp_radar.F
This commit corrects Fortran 2008 compliance issues in mp_radar.F that were
caught by the GNU Fortran compiler using the -std=f2008 flag. These issues are
related to the use of non-standard kind specifications and intrinsics. For
example:

  mp_radar.F:41:12:

     41 |  complex*16,public:: m_w_0, m_i_0
        |            1
  Error: GNU Extension: Nonstandard type declaration COMPLEX*16 at (1)

  ...

  mp_radar.F:138:37:

    138 |     xxdx(n) = dexp(dfloat(n-1)/dfloat(nrbins) &
        |                                     1
  Error: Function ‘dfloat’ at (1) has no IMPLICIT type

To provide standard kind specifications, local module variables R4KIND and
R8KIND, that should specify single- and double-precision, respectively, have
been defined as private parameters in module_libmassv.