Fix non-standard DFLOAT intrinsic in WRF physics module_mp_thompson.F
The module_mp_thompson.F code previously used DFLOAT to convert values to
double-precision reals, leading to errors from the GNU compiler when the
-std=f2008 flag is used:

   module_mp_thompson.F:3844:22:

    3844 |          Texp = DEXP( DFLOAT(k) - T_adjust*1.0D0 ) - 1.0D0
         |                      1
   Error: Function ‘dfloat’ at (1) has no IMPLICIT type

Using the REAL intrinsic with KIND=R8SIZE resolves these issues, and is made
easier by the fact that module_mp_thompson already defines R8SIZE.