Fix non-standard type declarations in WRF physics libmassv.F
The libmassv.F code contained several non-standard type declarations, as well
as some implicit declarations, that were pointed out by the GNU compilers,
e.g.,

   libmassv.F:6:13:

       6 |       real*8 x(*),y(*),z(*)
         |             1
   Error: GNU Extension: Nonstandard type declaration REAL*8 at (1)

and also by the NAG compiler, e.g.,

   Error: libmassv.F, line 6: KIND value (8) does not specify a valid representation method
   Errors in declarations, no further processing for VDIV
   Error: libmassv.F, line 16: KIND value (4) does not specify a valid representation method
   Errors in declarations, no further processing for VSDIV
   ...

To address these issues, two new macros are defined -- R4KIND and R8KIND -- to
provide kind-types that match MPAS's single-precision and double-precision kind
types. Macros were chosen, since the libmassv code is not a Fortran module and
avoiding adding the definition of, e.g., new parameters to the global namespace
is not desirable.