Fix order of dummy argument declarations in mpas_spline_interpolation.F
The mpas_spline_interpolation module contained argument lists in which arguments
were not always declared before they were used to dimension other array
arguments.

The GNU compiler pointed out these order-of-declaration issues with the
-std=f2008 option:

   mpas_spline_interpolation.F:118:31:

     118 |   real (kind=RKIND), dimension(n), intent(in) :: &
         |                               1
   Error: GNU Extension: Symbol ‘n’ is used before it is typed at (1)
   mpas_spline_interpolation.F:123:31:

     123 |   real (kind=RKIND), dimension(nOut), intent(in) :: &
         |                               1
   Error: GNU Extension: Symbol ‘nout’ is used before it is typed at (1)
   mpas_spline_interpolation.F:362:31:

     362 |   real (kind=RKIND), dimension(n), intent(in) :: &
         |                               1
   Error: GNU Extension: Symbol ‘n’ is used before it is typed at (1)
   mpas_spline_interpolation.F:366:31:

     366 |   real (kind=RKIND), dimension(nOut), intent(in) :: &
         |                               1
   Error: GNU Extension: Symbol ‘nout’ is used before it is typed at (1)

The simple fix involves reordering the declaration of dummy arguments, with no
changes needed to order of actual arguments.